config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root 'mail_sender#show'
  post 'send_email' => 'mail_sender#send_email'
  get 'users/index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  
  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/mail_sender_controller.rb
class MailSenderController < ApplicationController
  def show
  	@users = User.all
  end

  def send_email
  	if Rails.env.production?
  		begin
	  		RestClient.post "https://api:#{ENV['MAILGUN_API_KEY']}@api.mailgun.net/v2/#{ENV['MAILGUN_DOMAIN']}"+"/messages",
	  		    :from => "#{current_user.email}",
	  		    :to => "#{params[:to_email]}",
	  		    :subject => "#{params[:subject_email]}",
	  		    :text => "#{params[:content_email]}",
	  		    :html => "#{params[:content_email]}"
	  		flash[:success] = "Email Sent"
	  	rescue Exception => err
	  		flash[:danger] = "#{err}"
	  	end
  	else
  		flash[:info] = "Email is configured only for the production env."
  	end 
	redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mail_sender_helper.rb
module MailSenderHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header>
	<nav class="navbar navbar-inverse">
	  <div class="container-fluid">
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <%= link_to "MailGunMailer", root_path, id: "logo", class: "navbar-brand" %>
	    </div>

	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
	      <ul class="nav navbar-nav navbar-right">
	        <li><%= link_to "Home", root_path %></li>    
	        <% if user_signed_in? %>
	        <li><%= link_to "Users", users_index_path %></li>
	        <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
	        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
	        <% end %>
	      </ul>
	    </div>
	  </div>
	</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mailgunmailer</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
  </head>

  <body>
  	<%= render 'layouts/header' %>
    <p class="alert"><%= alert %></p>
    <div class="container">
    <% flash.each do |message_type, message|%>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    	<%= yield %>
    <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/mail_sender/show.html.erb
<div class="row">
	<div class="col-md-3">
		<div class="email-list">
		<h4>Email List:</h4>
			<% @users.each do |user| %>
				<% if user != current_user %>
					<div class="row">
						<div class="user-list">
								<%= user.name %>:<br>
								<%= user.email %>
						</div>
					</div>
				<% end %>
			<% end %>
		</div>
	</div>
	<div class="col-md-8 well well-lg">
		<div class="email-compose">
			<h3>Compose email here:</h3>
			<%= form_tag action: "send_email", method: 'post' do %>
				<div class="row">
				<table class="table">
					<tr>
						<td>From: </td> 
						<td><%= current_user.email %></td>
					</tr>
					<tr>
						<td>To: </td>
						<td><%= text_field_tag :to_email, params[:to_email], placeholder: 'To', required: true %></td>
					</tr>
					<tr>
						<td>Subject: </td>
						<td><%= text_field_tag :subject_email, params[:subject_email], placeholder: 'Subject', required: true %></td>
					</tr>
					<tr>
						<td colspan="2">
							<%= text_area_tag :content_email, params[:content_email],  class: 'col-md-8', placeholder: 'Composer Message here', size: '55x25', required: true %>
						
						</td>
					</tr>
				</table>
				</div>
				<div class="row">
					
				</div>
				<%= submit_tag "Send", class: 'btn btn-primary' %>
			<% end %>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<% @users.each do |user| %>
	<div class="row">
		<div class="user-list col-md-12 col-sm-12">
			<h3><%= user.name %></h3>
			<%= user.email %>
			<% if current_user.admin? && user != current_user %>
				<%= button_to "Delete user", user_registration_path, method: :delete, class: "btn btn-danger delete-user", data: {confirm: "You Sure?" } %>
		    <% end %>
		</div>
	</div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>